# access the hexo editor directly
local: true

# the username to login hexo editor
username: SuCicada

# the password for logining hexo editor
password: pengyifueman

# the blog directory
base_dir: ../

# port
port: 5000
